// Mocks generated by Mockito 5.4.4 from annotations
// in routes_mobile/test/domain/blocs/route_initialization_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:routes_mobile/data/services/cities_services.dart' as _i9;
import 'package:routes_mobile/data/services/countries_services.dart' as _i5;
import 'package:routes_mobile/data/services/route_executions_services.dart'
    as _i12;
import 'package:routes_mobile/data/services/routes_services.dart' as _i10;
import 'package:routes_mobile/data/services/states_services.dart' as _i8;
import 'package:routes_mobile/domain/entities/places/place_info.dart' as _i11;
import 'package:routes_mobile/domain/entities/places/zone.dart' as _i2;
import 'package:routes_mobile/domain/entities/routes/route_execution.dart'
    as _i4;
import 'package:routes_mobile/domain/entities/routes/transport_route.dart'
    as _i3;
import 'package:routes_mobile/domain/entities/routes/way_point.dart' as _i13;
import 'package:routes_mobile/utils/geolocation.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeZone_0 extends _i1.SmartFake implements _i2.Zone {
  _FakeZone_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransportRoute_1 extends _i1.SmartFake
    implements _i3.TransportRoute {
  _FakeTransportRoute_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteExecution_2 extends _i1.SmartFake
    implements _i4.RouteExecution {
  _FakeRouteExecution_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CountriesServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountriesServices extends _i1.Mock implements _i5.CountriesServices {
  @override
  _i6.Future<List<_i2.Country>> getCountries() => (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
        ),
        returnValue: _i6.Future<List<_i2.Country>>.value(<_i2.Country>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.Country>>.value(<_i2.Country>[]),
      ) as _i6.Future<List<_i2.Country>>);

  @override
  _i6.Future<_i2.Country> createCountry({
    required String? name,
    required String? iso,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCountry,
          [],
          {
            #name: name,
            #iso: iso,
          },
        ),
        returnValue: _i6.Future<_i2.Country>.value(_i7.dummyValue<_i2.Country>(
          this,
          Invocation.method(
            #createCountry,
            [],
            {
              #name: name,
              #iso: iso,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Country>.value(_i7.dummyValue<_i2.Country>(
          this,
          Invocation.method(
            #createCountry,
            [],
            {
              #name: name,
              #iso: iso,
            },
          ),
        )),
      ) as _i6.Future<_i2.Country>);
}

/// A class which mocks [StatesServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatesServices extends _i1.Mock implements _i8.StatesServices {
  @override
  _i6.Future<List<_i2.Zone>> getStatesByCountryId(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatesByCountryId,
          [id],
        ),
        returnValue: _i6.Future<List<_i2.Zone>>.value(<_i2.Zone>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.Zone>>.value(<_i2.Zone>[]),
      ) as _i6.Future<List<_i2.Zone>>);

  @override
  _i6.Future<_i2.Zone> createState({
    required String? name,
    required int? countryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createState,
          [],
          {
            #name: name,
            #countryId: countryId,
          },
        ),
        returnValue: _i6.Future<_i2.Zone>.value(_FakeZone_0(
          this,
          Invocation.method(
            #createState,
            [],
            {
              #name: name,
              #countryId: countryId,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Zone>.value(_FakeZone_0(
          this,
          Invocation.method(
            #createState,
            [],
            {
              #name: name,
              #countryId: countryId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Zone>);
}

/// A class which mocks [CitiesServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockCitiesServices extends _i1.Mock implements _i9.CitiesServices {
  @override
  _i6.Future<List<_i2.Zone>> getCitiesByStateId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCitiesByStateId,
          [id],
        ),
        returnValue: _i6.Future<List<_i2.Zone>>.value(<_i2.Zone>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.Zone>>.value(<_i2.Zone>[]),
      ) as _i6.Future<List<_i2.Zone>>);

  @override
  _i6.Future<_i2.Zone> createCity({
    required String? name,
    required int? stateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCity,
          [],
          {
            #name: name,
            #stateId: stateId,
          },
        ),
        returnValue: _i6.Future<_i2.Zone>.value(_FakeZone_0(
          this,
          Invocation.method(
            #createCity,
            [],
            {
              #name: name,
              #stateId: stateId,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Zone>.value(_FakeZone_0(
          this,
          Invocation.method(
            #createCity,
            [],
            {
              #name: name,
              #stateId: stateId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Zone>);
}

/// A class which mocks [RoutesServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutesServices extends _i1.Mock implements _i10.RoutesServices {
  @override
  _i6.Future<List<_i3.TransportRoute>> getRoutesByCityId(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoutesByCityId,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i3.TransportRoute>>.value(<_i3.TransportRoute>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.TransportRoute>>.value(<_i3.TransportRoute>[]),
      ) as _i6.Future<List<_i3.TransportRoute>>);

  @override
  _i6.Future<_i3.TransportRoute> createRoute({
    required String? name,
    required String? description,
    required int? cityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoute,
          [],
          {
            #name: name,
            #description: description,
            #cityId: cityId,
          },
        ),
        returnValue: _i6.Future<_i3.TransportRoute>.value(_FakeTransportRoute_1(
          this,
          Invocation.method(
            #createRoute,
            [],
            {
              #name: name,
              #description: description,
              #cityId: cityId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.TransportRoute>.value(_FakeTransportRoute_1(
          this,
          Invocation.method(
            #createRoute,
            [],
            {
              #name: name,
              #description: description,
              #cityId: cityId,
            },
          ),
        )),
      ) as _i6.Future<_i3.TransportRoute>);

  @override
  _i6.Future<List<_i3.TransportRoute>> getByPlaceInfo(
          {required _i11.PlaceInfo? info}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPlaceInfo,
          [],
          {#info: info},
        ),
        returnValue:
            _i6.Future<List<_i3.TransportRoute>>.value(<_i3.TransportRoute>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.TransportRoute>>.value(<_i3.TransportRoute>[]),
      ) as _i6.Future<List<_i3.TransportRoute>>);
}

/// A class which mocks [RouteExecutionsServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteExecutionsServices extends _i1.Mock
    implements _i12.RouteExecutionsServices {
  @override
  _i6.Future<List<_i4.RouteExecution>> getExecutionsByRouteId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExecutionsByRouteId,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i4.RouteExecution>>.value(<_i4.RouteExecution>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.RouteExecution>>.value(<_i4.RouteExecution>[]),
      ) as _i6.Future<List<_i4.RouteExecution>>);

  @override
  _i6.Future<_i4.RouteExecution> createExecution({
    required String? licensePlate,
    required DateTime? initTime,
    required String? routeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExecution,
          [],
          {
            #licensePlate: licensePlate,
            #initTime: initTime,
            #routeId: routeId,
          },
        ),
        returnValue: _i6.Future<_i4.RouteExecution>.value(_FakeRouteExecution_2(
          this,
          Invocation.method(
            #createExecution,
            [],
            {
              #licensePlate: licensePlate,
              #initTime: initTime,
              #routeId: routeId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.RouteExecution>.value(_FakeRouteExecution_2(
          this,
          Invocation.method(
            #createExecution,
            [],
            {
              #licensePlate: licensePlate,
              #initTime: initTime,
              #routeId: routeId,
            },
          ),
        )),
      ) as _i6.Future<_i4.RouteExecution>);

  @override
  _i6.Future<_i4.RouteExecution> updateExecution({
    required String? routeId,
    required DateTime? endTime,
    required List<_i13.WayPoint>? wayPoints,
    required int? routeExecutionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExecution,
          [],
          {
            #routeId: routeId,
            #endTime: endTime,
            #wayPoints: wayPoints,
            #routeExecutionId: routeExecutionId,
          },
        ),
        returnValue: _i6.Future<_i4.RouteExecution>.value(_FakeRouteExecution_2(
          this,
          Invocation.method(
            #updateExecution,
            [],
            {
              #routeId: routeId,
              #endTime: endTime,
              #wayPoints: wayPoints,
              #routeExecutionId: routeExecutionId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.RouteExecution>.value(_FakeRouteExecution_2(
          this,
          Invocation.method(
            #updateExecution,
            [],
            {
              #routeId: routeId,
              #endTime: endTime,
              #wayPoints: wayPoints,
              #routeExecutionId: routeExecutionId,
            },
          ),
        )),
      ) as _i6.Future<_i4.RouteExecution>);
}

/// A class which mocks [Geolocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocation extends _i1.Mock implements _i14.Geolocation {
  @override
  _i6.Future<_i11.PlaceInfo?> getPlaceInfoFromLocation(
          {_i15.LatLng? location}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaceInfoFromLocation,
          [],
          {#location: location},
        ),
        returnValue: _i6.Future<_i11.PlaceInfo?>.value(),
        returnValueForMissingStub: _i6.Future<_i11.PlaceInfo?>.value(),
      ) as _i6.Future<_i11.PlaceInfo?>);

  @override
  _i6.Future<_i13.WayPoint?> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i6.Future<_i13.WayPoint?>.value(),
        returnValueForMissingStub: _i6.Future<_i13.WayPoint?>.value(),
      ) as _i6.Future<_i13.WayPoint?>);

  @override
  _i6.Future<void> addOnChanged(
          dynamic Function(_i13.DirectionedWayPoint)? onChanged) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOnChanged,
          [onChanged],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopOnChanged() => (super.noSuchMethod(
        Invocation.method(
          #stopOnChanged,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
